# Generated by Django 3.1.3 on 2020-11-30 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
